name: Armor
main: me.Joeyy.Armor.Armor
version: 0.1
commands:
  equiparmor:
    description: Automaticly equips you with the desired type of armor.
    usage: "Usage: '/equiparmor TYPE <player>' Replace type with leather/chainmail/iron/gold/diamond."
